// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: box.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GetPictureAck;
@class GetPictureRequest;
@class SendMessageAck;
@class SendMessageRequest;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Box_Service

typedef GPB_ENUM(Box_Service) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Box_Service_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Box_Service_HeartBeat = 0,
  Box_Service_SendMesaage = 1,
  Box_Service_SendMesaageResponse = 2,
  Box_Service_GetPicture = 3,
  Box_Service_GetPictureResponse = 4,
};

GPBEnumDescriptor *Box_Service_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Box_Service_IsValidValue(int32_t value);

#pragma mark - Enum Box_Code

typedef GPB_ENUM(Box_Code) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Box_Code_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Box_Code_Sucess = 0,
  Box_Code_AuthError = 1,
};

GPBEnumDescriptor *Box_Code_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Box_Code_IsValidValue(int32_t value);

#pragma mark - BoxRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BoxRoot : GPBRootObject
@end

#pragma mark - Box

typedef GPB_ENUM(Box_FieldNumber) {
  Box_FieldNumber_Code = 1,
  Box_FieldNumber_Msg = 2,
  Box_FieldNumber_Service = 3,
  Box_FieldNumber_SendMessageRequest = 11,
  Box_FieldNumber_GetPictureRequest = 12,
  Box_FieldNumber_SendMessageAck = 51,
  Box_FieldNumber_GetPictureAck = 52,
};

typedef GPB_ENUM(Box_DataAck_OneOfCase) {
  Box_DataAck_OneOfCase_GPBUnsetOneOfCase = 0,
  Box_DataAck_OneOfCase_SendMessageRequest = 11,
  Box_DataAck_OneOfCase_GetPictureRequest = 12,
};

typedef GPB_ENUM(Box_DataRequest_OneOfCase) {
  Box_DataRequest_OneOfCase_GPBUnsetOneOfCase = 0,
  Box_DataRequest_OneOfCase_SendMessageAck = 51,
  Box_DataRequest_OneOfCase_GetPictureAck = 52,
};

@interface Box : GPBMessage

@property(nonatomic, readwrite) Box_Code code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite) Box_Service service;

/** 响应报文 */
@property(nonatomic, readonly) Box_DataAck_OneOfCase dataAckOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) SendMessageRequest *sendMessageRequest;

@property(nonatomic, readwrite, strong, null_resettable) GetPictureRequest *getPictureRequest;

/** 发送报文 */
@property(nonatomic, readonly) Box_DataRequest_OneOfCase dataRequestOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) SendMessageAck *sendMessageAck;

@property(nonatomic, readwrite, strong, null_resettable) GetPictureAck *getPictureAck;

@end

/**
 * Fetches the raw value of a @c Box's @c code property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Box_Code_RawValue(Box *message);
/**
 * Sets the raw value of an @c Box's @c code property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBox_Code_RawValue(Box *message, int32_t value);

/**
 * Fetches the raw value of a @c Box's @c service property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Box_Service_RawValue(Box *message);
/**
 * Sets the raw value of an @c Box's @c service property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBox_Service_RawValue(Box *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'dataAck'.
 **/
void Box_ClearDataAckOneOfCase(Box *message);
/**
 * Clears whatever value was set for the oneof 'dataRequest'.
 **/
void Box_ClearDataRequestOneOfCase(Box *message);

#pragma mark - SendMessageRequest

typedef GPB_ENUM(SendMessageRequest_FieldNumber) {
  SendMessageRequest_FieldNumber_Message = 1,
};

@interface SendMessageRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

#pragma mark - SendMessageAck

typedef GPB_ENUM(SendMessageAck_FieldNumber) {
  SendMessageAck_FieldNumber_AckMessage = 1,
};

@interface SendMessageAck : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ackMessage;

@end

#pragma mark - GetPictureRequest

typedef GPB_ENUM(GetPictureRequest_FieldNumber) {
  GetPictureRequest_FieldNumber_URL = 1,
};

@interface GetPictureRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

#pragma mark - GetPictureAck

typedef GPB_ENUM(GetPictureAck_FieldNumber) {
  GetPictureAck_FieldNumber_PictureData = 1,
};

@interface GetPictureAck : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *pictureData;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
